AWSTemplateFormatVersion: 2010-09-09
Parameters:
    pS3bktName:
        Type: String    
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
        BucketName: !Ref pS3bktName
        VersioningConfiguration:
        Status: Enabled