AWSTemplateFormatVersion: 2010-09-09
Parameters:
  pEnv:
    Type: String
    Description: Type of the AWS account
    Default: dev
  pProjectName:
    Type: String
    Description: The name of the project being built.  This name will be used on a number of resources.
    Default: pge-crm
  pResourceName:
    Type: String
    Description: The name of the resource being created
    Default: rds 
  pGitHubOwner:
    Type: String
    Default: pgetech
    AllowedPattern: 'pgetech'
  pPipelineArtifactsBucket:
    Type: String
    Description: The name of s3 bucket which store the artifacts.
    Default: "pge-crm-cicd-artifacts"
  pGitHubRepo:
    Type: String
    Default: pge-crm-ecm-cloud-infra-ci
  pNotifyStatusSNSARN:
    Description: SSM Parameter for Notification
    Type : AWS::SSM::Parameter::Value<String>
    Default: /general/CodePipeline/SNSTopic/Status
  pApprovalSNS:
    Description: SSM Parameter for Notification
    Type : AWS::SSM::Parameter::Value<String>
    Default: /general/CodePipeline/SNSTopic/Approval
  pVPCID:
    Description: Provide the VPC Details
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/vpc/id"  
  pGitHubBranch:
    Type: String 
  pEncryptionKeyArn:
    Type: AWS::SSM::Parameter::Value<String> 
  # Buildspec Template CFT and Value parameters
  pTemplatePath:
    Type: String 
  pValuesPath:
    Type: String
  pSGTemplatePath:
    Type: String 
  pSGValuesPath:
    Type: String
  # Buildspec parameters are mentioned here
  pBuildSpecFile:
    Type: String
  pBuildSpecFileVerify:
    Type: String   
  pEnvironment:
    Description: 'SSM Parameter for Environmeent'
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/general/environment"
  pAppID:
    Description: 'Enter the Application ID'
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/general/appid"
  pOwner:
    Description: 'Enter the Owner Details'
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/general/owner"
  pCompliance:
    Description: 'Enter the Compliance'
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/general/Compliance"
  pNotify:
    Description: 'Enter the Notification E-Mail Id'
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/general/notify"
  pDataClassification:
    Description: 'Enter the Data Classification details'
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/general/DataClassification"
  pCRIS:
    Description: 'Enter the CRIS details'
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/general/CRIS"
    # Private Subnets - Added to  Codebuild Verify
  pRDSPrivateSubnetIDinAZ1:
    Description: Provide the RDS Private Subnet ID In Availability Zone 1     
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vpc/2/privatesubnet1/id 
  pRDSPrivateSubnetIDinAZ2:
    Description: Provide the RDS Private Subnet ID In Availability Zone 2     
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vpc/2/privatesubnet2/id
  pRDSPrivateSubnetIDinAZ3:
    Description: Provide the RDS Private Subnet ID In Availability Zone 3     
    Type: AWS::SSM::Parameter::Value<String>
    Default: /vpc/2/privatesubnet3/id 
  
Resources:  
  rCodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${pProjectName}-${pEnv}-${pResourceName}-codebuild-role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: 'sts:AssumeRole'
  rCodeBuildPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub '${pProjectName}-${pEnv}-${pResourceName}-codebuild-policy'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogGroups
            - logs:FilterLogEvents
            - logs:DescribeLogStreams
            - logs:DeleteLogGroup
            - s3:putObject
            - s3:getObject
            - codebuild:*
            - s3:*
            - ssm:*
            - sns:*
            - kms:*
            - cloudformation:*
            - ec2:*
            - secretsmanager:*
            - rds:*
          Resource: "*"
      Roles:
        -  !Ref rCodeBuildRole

  rCodePipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${pProjectName}-${pEnv}-${pResourceName}-codepipeline-role'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: 'sts:AssumeRole'
  rCodePipelinePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: !Sub '${pProjectName}-${pEnv}-${pResourceName}-codepipeline-policy'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
            - Effect: Allow
              Action:
                - s3:putObject
                - s3:getObject
                - codebuild:StartBuild
                - codebuild:BatchGetBuilds
                - codestar-connections:UseConnection
                - cloudformation:*
                - s3:*
                - ssm:*
                - sns:*
                - kms:*
                - elasticfilesystem:*
                - cloudformation:*
                - ec2:*
                - secretsmanager:*
                - codestar:*
              Resource:
                 - "*"
            - Effect: Allow
              Action:
                - cloudformation:CreateStack
                - cloudformation:DescribeStacks
                - cloudformation:DeleteStack
                - cloudformation:UpdateStack
                - cloudformation:CreateChangeSet
                - cloudformation:ExecuteChangeSet
                - cloudformation:DeleteChangeSet
                - cloudformation:DescribeChangeSet
                - cloudformation:ValidateTemplate
              Resource: "*"
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource: !GetAtt rCodePipelineRole.Arn
      Roles:
        -  !Ref rCodePipelineRole 
  
  rCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${pProjectName}-${pEnv}-${pResourceName}-codebuild-project
      ServiceRole: !Ref rCodeBuildRole
      EncryptionKey: !Ref pEncryptionKeyArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref pBuildSpecFile
      Environment:
        Type: LINUX_CONTAINER
        # ComputeType options: BUILD_GENERAL1_SMALL, BUILD_GENERAL1_MEDIUM, BUILD_GENERAL1_LARGE
        ComputeType: BUILD_GENERAL1_SMALL
        # Run `aws codebuild list-curated-environment-images` for a complete list of images provided.
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:3.0"
        EnvironmentVariables:
        - Name: CF_TEMPLATE
          Type: PLAINTEXT
          Value: !Ref pTemplatePath
        - Name: CF_TEMPLATE_VALUES
          Type: PLAINTEXT
          Value: !Ref pValuesPath
        - Name: SG_CF_TEMPLATE
          Type: PLAINTEXT
          Value: !Ref pSGTemplatePath
        - Name: SG_CF_TEMPLATE_VALUES
          Type: PLAINTEXT
          Value: !Ref pSGValuesPath
        - Name: SNS_MESSAGE
          Type: PLAINTEXT
          Value: rds/pipeline/sns-message.txt
        - Name: SNS_TOPIC__ARN_NOTIFY_STATUS
          Type: PLAINTEXT
          Value: !Ref pNotifyStatusSNSARN
        - Name: CF_TAGS_FILE_PATH
          Type: PLAINTEXT
          Value: tags.json
        - Name: SNS_MESSAGE_VERIFY
          Type: PLAINTEXT
          Value: rds/pipeline/sns-message-verify.txt
      Artifacts:
        Type: CODEPIPELINE
      TimeoutInMinutes: 20
      Tags:
        - Key: AppID
          Value: !Ref pAppID
        - Key: Environment
          Value: !Ref pEnvironment
        - Key: Owner
          Value: !Ref pOwner
        - Key: Compliance
          Value: !Ref pCompliance
        - Key: Notify
          Value: !Ref pNotify
        - Key: DataClassification
          Value: !Ref pDataClassification
        - Key: CRIS
          Value: !Ref pCRIS 
  rCodeBuildVerify:
    DependsOn:
      - rCodeBuildPolicy
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${pProjectName}-${pEnv}-${pResourceName}-codebuildverify-project
      ServiceRole: !Ref rCodeBuildRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref pBuildSpecFileVerify
      Environment:
        Type: LINUX_CONTAINER
        # ComputeType options: BUILD_GENERAL1_SMALL, BUILD_GENERAL1_MEDIUM, BUILD_GENERAL1_LARGE
        ComputeType: BUILD_GENERAL1_SMALL
        # Run `aws codebuild list-curated-environment-images` for a complete list of images provided.
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:3.0"
        EnvironmentVariables:        
        - Name: CF_TEMPLATE_VALUES
          Type: PLAINTEXT
          Value: !Ref pValuesPath             
      Artifacts:
        Type: CODEPIPELINE
      TimeoutInMinutes: 20
      VpcConfig:
        VpcId: !Ref pVPCID
        Subnets: [!Ref pRDSPrivateSubnetIDinAZ1, !Ref pRDSPrivateSubnetIDinAZ2, !Ref pRDSPrivateSubnetIDinAZ3]
        SecurityGroupIds: [!Ref rCodeBuildRDSSecurityGroup]
      Tags:
        - Key: AppID
          Value: !Ref pAppID
        - Key: Environment
          Value: !Ref pEnvironment
        - Key: Owner
          Value: !Ref pOwner
        - Key: Compliance
          Value: !Ref pCompliance
        - Key: Notify
          Value: !Ref pNotify
        - Key: DataClassification
          Value: !Ref pDataClassification
        - Key: CRIS
          Value: !Ref pCRIS  
  rCodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref pPipelineArtifactsBucket
        EncryptionKey: 
          Id:  !Ref pEncryptionKeyArn
          Type: KMS        
      RestartExecutionOnUpdate: true
      Name: !Sub '${pProjectName}-${pEnv}-${pResourceName}-CodePipeline'
      RoleArn: !Join [ "", ["arn:aws:iam::", !Ref "AWS::AccountId", ":role/", !Ref rCodePipelineRole  ] ]
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              InputArtifacts: []
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: SourceCode
              Configuration:
                Owner: !Ref pGitHubOwner
                Repo: !Ref pGitHubRepo
                Branch: !Ref pGitHubBranch
                PollForSourceChanges: false
                OAuthToken: '{{resolve:secretsmanager:drc/github/accesskey:SecretString:github-accesskey}}'
              Namespace: SourceVariables
              RunOrder: 1
        # Stage 2:  Upon Approval Instance would be provisioned
        
        - Name: !Sub Create-${pResourceName}
          Actions:
            - Name: ApprovalForProvisioning
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: 1
                Provider: Manual
              Configuration:           
                NotificationArn: !Ref pApprovalSNS
                #https://github.com/pgetech/pge-ecm-drccloud-infra-ci/commit/f0b90df19cb38fcc4a672787f28b3ec7b0dcb358
                ExternalEntityLink: !Join [ "/", ["https://github.com", !Ref pGitHubOwner, !Ref pGitHubRepo, "commit", "#{SourceVariables.CommitId}"]]
                CustomData: "The RDS pipeline would have these changes been deployed #{SourceVariables.CommitMessage}"
              RunOrder: 1         
            - Name: !Sub 'Provision-RDS'
              RunOrder: 2
              InputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName:  !Ref rCodeBuild
              OutputArtifacts:
                - Name: BuildArtifact
        - Name: !Sub Verify-${pResourceName}
          Actions:    
            - Name: !Sub 'Verify-Database'
              RunOrder: 1
              InputArtifacts:
                - Name: SourceCode
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName:  !Ref rCodeBuildVerify
              OutputArtifacts:
                - Name: BuildArtifactVerify             
        
  rCodeBuildRDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to RDS Aurora Serverless
      GroupName: pge-crm-rds-cicd-codebuild-sg
      VpcId:
        Ref: pVPCID
      # Allow Outbound All traffic 0.0.0.0/0              
      SecurityGroupEgress:
        - IpProtocol: '-1'     
          CidrIp: 0.0.0.0/0                   
  rCodeStarNotification:
    Type: 'AWS::CodeStarNotifications::NotificationRule'
    Properties:
      Name: !Sub '${pProjectName}-${pResourceName}-CodeStarNotification'
      DetailType: FULL
      Resource: !Join [ "", ["arn:aws:codepipeline:", !Ref "AWS::Region", ":", !Ref "AWS::AccountId", ":", !Sub '${pProjectName}-${pEnv}-${pResourceName}-CodePipeline']]
      EventTypeIds: 
        - codepipeline-pipeline-action-execution-failed
        - codepipeline-pipeline-pipeline-execution-failed  
      Targets: 
        - TargetType: SNS 
          TargetAddress: !Ref pNotifyStatusSNSARN
      Tags: 
        AppID: !Ref pAppID
        Environment: !Ref pEnvironment 
  rGithubWebhookRDScft:
    Type: 'AWS::CodePipeline::Webhook'
    Properties:
      RegisterWithThirdParty: 'true'
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: '{{resolve:secretsmanager:drc/github/accesskey:SecretString:github-accesskey}}'
      Filters:
      - JsonPath: "$.ref"
        MatchEquals: "refs/heads/main"
      - JsonPath: "$.commits[*].*[?(@ == 'rds/rds-cft-values.json')]"  
        MatchEquals: rds/rds-cft-values.json
      TargetPipeline: !Ref rCodePipeline
      TargetAction: Source
      TargetPipelineVersion: !GetAtt rCodePipeline.Version
  rRDSSecurityGroupParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /CodeBuild/aurora/SecurityGroup
      Type: String    
      Value: !Ref rCodeBuildRDSSecurityGroup
      Description: SSM Parameter for RDS Security Group
      Tags:
        AppID: !Ref pAppID
        Environment: !Ref pEnvironment
        Owner: !Ref pOwner
        Compliance: !Ref pCompliance
        Notify: !Ref pNotify
        DataClassification: !Ref pDataClassification
        CRIS: !Ref pCRIS
 
