version: 0.2
env:
  variables:
    CF_TAGS_FILE_PATH: ./tags.json
phases:
  install:
    commands:
      #Install the cfn-lint plugin
      - pip install cfn-lint
  pre_build:
    commands:
      - echo "pre build"
      - cfn-lint $CNAME_CF_TEMPLATE      
     
  build:
    commands:
       - echo "build stage"
       - ls -lrth
       - echo $CNAME_CF_TEMPLATE
       - echo $CNAME_CF_TEMPLATE_VALUES
       - export CNAME_STACK=$(cat $CNAME_CF_TEMPLATE_VALUES | jq .[0] | jq 'split("=")' | jq -r .[1])
       - CERT_NAME=$(cat $CNAME_CF_TEMPLATEVALUES | jq .[2] | jq 'split("=")' | jq -r .[1])
       - echo $PRIVATE_HOSTED_ZONEID
       - echo $
        
         #Add the dev to the CNAME_NAME
        
       #- chmod 775 scripts/create_update_stack.sh
       #Update the CNAME_NAME with env
       - aws cloudformation deploy --stack-name  ${CNAME_STACK} --region us-east-1  --template-file $CNAME_CF_TEMPLATE --parameter-overrides file://$CNAME_CF_TEMPLATE_VALUES --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --tags file://$CF_TAGS_FILE_PATH   
       #- ./scripts/create_update_stack.sh ${BUCKET_NAME}-Stack $S3_CF_TEMPLATE $S3_CF_TEMPLATE_VALUES
    
  post_build:
    commands:
       - bash -c "if [ /"$CODEBUILD_BUILD_SUCCEEDING/" == /"0/" ]; then exit 1; fi"
       - echo "post_build" 
       # Verify the resource created    
       - sed -i "s/@CNAME_STACK@/$CNAME_STACK/g" $SNS_MESSAGE
       - sed -i "s/@CERT_NAME@/$CERT_NAME/g" $SNS_MESSAGE    
       - cat $SNS_MESSAGE
       - aws sns publish --topic-arn $SNS_TOPIC__ARN_NOTIFY_STATUS --subject  "AWS CNAME Create/Update Status" --message file://$SNS_MESSAGE   

