version: 0.2
phases:
  install:
    commands:
      #Install the cfn-lint plugin
      - echo 'Install'
      - pip install cfn-lint
  pre_build:
    commands:
      - echo "pre build"
      - cfn-lint $EFS_CF_TEMPLATE
      - cfn-lint $EFS_CF_SG_TEMPLATE      
     
  build:
    commands:
      - echo "build stage"  
      
      - echo $EFS_CF_SG_TEMPLATE
      - echo $EFS_CF_TEMPLATE
      - echo $EFS_CF_TEMPLATE_VALUES
      - echo $EFS_SG_CF_TEMPLATE_VALUES
      
      
      - export EFS_TYPE=$(cat $EFS_CF_TEMPLATE_VALUES | jq .[0] | jq 'split("=")' | jq -r .[1])
      - export ENV=$(cat $EFS_CF_TEMPLATE_VALUES | jq .[1] | jq 'split("=")' | jq -r .[1])
      - echo $EFS_TYPE
      - echo $ENV
      - export SG_STACK_NAME=pge-crm-efs-sg-$ENV-stack
      - export EFS_STACK_NAME=pge-crm-efs-$EFS_TYPE-$ENV-stack
      - echo $SG_STACK_NAME
      - echo $EFS_STACK_NAME

      #Create Security group      
      - aws cloudformation deploy --stack-name $SG_STACK_NAME --template-file $EFS_CF_SG_TEMPLATE --parameter-overrides file://$EFS_SG_CF_TEMPLATE_VALUES --tags file://$CF_TAGS_FILE_PATH
                  
      #Creating EFS
      - aws cloudformation deploy --stack-name $EFS_STACK_NAME --template-file $EFS_CF_TEMPLATE --parameter-overrides file://$EFS_CF_TEMPLATE_VALUES --tags file://$CF_TAGS_FILE_PATH
            
  post_build:
    commands:
       - if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 0 ]; then echo "ERROR BUILD FAILED " && exit 1 ; fi

       - echo "post_build" 
       - echo "Validate AWS EFS"     
       
       # From the outputs of the stack get the FileSystem Id.
       - export EFS_FS_ID=$(aws cloudformation describe-stacks --stack-name $EFS_STACK_NAME | jq ."Stacks" | jq ".[].Outputs" | jq .[1].OutputValue) 
       - sed -i "s/@EFS_FileSystem_ID@/$EFS_FS_ID/g" $SNS_MESSAGE    
       - cat $SNS_MESSAGE
       - aws sns publish --topic-arn $SNS_TOPIC__ARN_NOTIFY_STATUS --subject  "AWS EFS Create/Update Status" --message file://$SNS_MESSAGE          

